### ISSUE TITLE
TIMER not found

### ISSUE THREAD

**Issue by vikrantvm** [rukshn/pomodoro#3]
get this error, any suggestions?

```
$ pomo                   
POMODORO in YA TERMINAL
TIMER SET FOR 25 MINUTES
pomo:61: = not found
```

**Comment by rukshn** [comment]
Have you tried this with other commands like 

`$ pomo -s`
`$ pomo -l`

Does this error only come up when trying 

`$ pomo`

Also is this on Mac or Linux? Do you have terminal-notifier installed in mac?

**Comment by unaitxu** [comment]
Same error here on a Mac, with and without terminal-notifier installed.

**Comment by vikrantvm** [comment]
I'm working on OSX. Also tried with terminal notifier on, get the same error with `pomo -s` and `pomo -l`.

**Comment by zaphod65** [comment]
@vikrantvm are you using ZSH?  I have the same issue but running the commands in bash rather than ZSH seemed to fix the issue...

**Comment by vikrantvm** [comment]
Ah, I see. Nice catch, I am using zsh. going back to bash fixes that.

**Comment by zaphod65** [comment]
@vikrantvm @unaitxu After a little experimentation I've gotten it working in ZSH on OSX, and I've forked it to my own account but I'm not 100% on PR-ing it back to the main branch as it might not be completely compatible with other versions; some ZSH documentation recommends using the '==' equality operator, so I don't know if this error is unique to the current OSX build of ZSH or not.

@rukshn Thoughts?
